#!/usr/bin/env python2

import sys
from multiplier.multiplication import multiply

def main():
    if len(sys.argv) != 3:
        print >>sys.stderr, 'usage:', sys.argv[0], 'x', 'y'
        print >>sys.stderr, 'multiply x by y'
        sys.exit(1)
    print multiply(int(sys.argv[1]), int(sys.argv[2]))

if __name__ == '__main__':
    main()
